// <auto-generated />
using System;
using BloodHeroA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodHeroA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BloodHeroA.Models.Entities.BankingOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("TotalDonations")
                        .HasColumnType("int");

                    b.Property<int>("TotalExpired")
                        .HasColumnType("int");

                    b.Property<int>("TotalRelease")
                        .HasColumnType("int");

                    b.Property<int>("TotalStorage")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BankingOrganizations");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BloodInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredUnits")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("RecipientOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReleasedUnits")
                        .HasColumnType("int");

                    b.Property<int>("StoredUnits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BloodInventories");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BloodStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DonationRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExpiryProcess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ReleasedId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("int");

                    b.Property<int>("UnitStored")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankingOrganizationId");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.ToTable("BloodStorages");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BloodTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int>("Cancer")
                        .HasColumnType("int");

                    b.Property<int>("ChronicDisease")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("HIV")
                        .HasColumnType("int");

                    b.Property<int>("HeartDisease")
                        .HasColumnType("int");

                    b.Property<int>("Hemophilic")
                        .HasColumnType("int");

                    b.Property<int>("HepatitisB")
                        .HasColumnType("int");

                    b.Property<int>("IVDrugConsumer")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SevereLungsDisease")
                        .HasColumnType("int");

                    b.Property<int>("Syphilis")
                        .HasColumnType("int");

                    b.Property<int>("Tattoo")
                        .HasColumnType("int");

                    b.Property<string>("TestRemark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BankingOrganizationId");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.ToTable("BloodTestResults");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BloodStorageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BloodTestResultId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonatedBloodType")
                        .HasColumnType("int");

                    b.Property<string>("DonationRemark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DonorOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStored")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTested")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UnitsDonated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankingOrganizationId");

                    b.HasIndex("DonorId");

                    b.HasIndex("DonorOrganizationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodTypeNeeded")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RecipientOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRemained")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRequested")
                        .HasColumnType("int");

                    b.Property<int>("UnitsSupplied")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankingOrganizationId");

                    b.HasIndex("RecipientOrganizationId");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int?>("Cancer")
                        .HasColumnType("int");

                    b.Property<int?>("ChronicDisease")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DonorOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HIV")
                        .HasColumnType("int");

                    b.Property<int?>("HeartDisease")
                        .HasColumnType("int");

                    b.Property<int?>("Hemophilic")
                        .HasColumnType("int");

                    b.Property<int?>("HepatitisB")
                        .HasColumnType("int");

                    b.Property<int>("IVDrugConsumer")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastDonationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NextDueDonationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("SevereLungsDisease")
                        .HasColumnType("int");

                    b.Property<int>("StateOfOrigin")
                        .HasColumnType("int");

                    b.Property<int?>("Syphilis")
                        .HasColumnType("int");

                    b.Property<int>("Tattoo")
                        .HasColumnType("int");

                    b.Property<int>("TotalDonations")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DonorOrganizationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonorOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("TotalDonations")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegisteredDonors")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DonorOrganizations");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.RecipientOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecievedBlood")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RecipientOrganizations");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.ReleasedBlood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("BloodStorageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DonationRequestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReasonForRelease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RecipientOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitsReleased")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankingOrganizationId");

                    b.HasIndex("DonationRequestId");

                    b.HasIndex("RecipientOrganizationId");

                    b.ToTable("ReleasedBloods");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BankingOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DonorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DonorOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashPassWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RecipientOrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd38778b-eab3-4107-82f3-81e2c9d0f4d9"),
                            CreatedAt = new DateTime(2026, 3, 13, 20, 56, 20, 616, DateTimeKind.Utc).AddTicks(1346),
                            Email = "admin@bloodhero.com",
                            FullName = "BloodHero Admin",
                            HashPassWord = "$2a$11$6oa/w00m3.g4NkrAqjNH9eORe/7vKmeLs4Cpn2xvJLGE3zq4TKlmG",
                            IsAvailable = true,
                            IsDeleted = false,
                            PhoneNumber = "07043138331",
                            Role = 1
                        });
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BankingOrganization", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.User", "User")
                        .WithOne("BankingOrganization")
                        .HasForeignKey("BloodHeroA.Models.Entities.BankingOrganization", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BloodStorage", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.BankingOrganization", "BankingOrganization")
                        .WithMany("BloodStorages")
                        .HasForeignKey("BankingOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.Donation", "Donation")
                        .WithOne("BloodStorage")
                        .HasForeignKey("BloodHeroA.Models.Entities.BloodStorage", "DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankingOrganization");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BloodTestResult", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.BankingOrganization", "BankingOrganization")
                        .WithMany("BloodTestResults")
                        .HasForeignKey("BankingOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.Donation", "Donation")
                        .WithOne("BloodTestResult")
                        .HasForeignKey("BloodHeroA.Models.Entities.BloodTestResult", "DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankingOrganization");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donation", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.BankingOrganization", "BankingOrganization")
                        .WithMany("Donations")
                        .HasForeignKey("BankingOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.DonorOrganization", "DonorOrganization")
                        .WithMany("Donations")
                        .HasForeignKey("DonorOrganizationId");

                    b.Navigation("BankingOrganization");

                    b.Navigation("Donor");

                    b.Navigation("DonorOrganization");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonationRequest", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.BankingOrganization", "BankingOrganization")
                        .WithMany("DonationRequests")
                        .HasForeignKey("BankingOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.RecipientOrganization", "RecipientOrganization")
                        .WithMany("DonationRequests")
                        .HasForeignKey("RecipientOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankingOrganization");

                    b.Navigation("RecipientOrganization");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donor", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.DonorOrganization", "DonorOrganization")
                        .WithMany("Donors")
                        .HasForeignKey("DonorOrganizationId");

                    b.HasOne("BloodHeroA.Models.Entities.User", "User")
                        .WithOne("Donor")
                        .HasForeignKey("BloodHeroA.Models.Entities.Donor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorOrganization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonorOrganization", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.User", "User")
                        .WithOne("DonorOrganization")
                        .HasForeignKey("BloodHeroA.Models.Entities.DonorOrganization", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Notification", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.User", "Receiver")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.User", "Sender")
                        .WithMany("SentNotifications")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.RecipientOrganization", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.User", "User")
                        .WithOne("RecipientOrganization")
                        .HasForeignKey("BloodHeroA.Models.Entities.RecipientOrganization", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.ReleasedBlood", b =>
                {
                    b.HasOne("BloodHeroA.Models.Entities.BankingOrganization", "BankingOrganization")
                        .WithMany("ReleasedBloods")
                        .HasForeignKey("BankingOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodHeroA.Models.Entities.DonationRequest", "DonationRequest")
                        .WithMany("ReleasedBloods")
                        .HasForeignKey("DonationRequestId");

                    b.HasOne("BloodHeroA.Models.Entities.RecipientOrganization", "RecipientOrganization")
                        .WithMany("ReleasedBloods")
                        .HasForeignKey("RecipientOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankingOrganization");

                    b.Navigation("DonationRequest");

                    b.Navigation("RecipientOrganization");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.BankingOrganization", b =>
                {
                    b.Navigation("BloodStorages");

                    b.Navigation("BloodTestResults");

                    b.Navigation("DonationRequests");

                    b.Navigation("Donations");

                    b.Navigation("ReleasedBloods");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donation", b =>
                {
                    b.Navigation("BloodStorage");

                    b.Navigation("BloodTestResult");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonationRequest", b =>
                {
                    b.Navigation("ReleasedBloods");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.DonorOrganization", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Donors");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.RecipientOrganization", b =>
                {
                    b.Navigation("DonationRequests");

                    b.Navigation("ReleasedBloods");
                });

            modelBuilder.Entity("BloodHeroA.Models.Entities.User", b =>
                {
                    b.Navigation("BankingOrganization");

                    b.Navigation("Donor");

                    b.Navigation("DonorOrganization");

                    b.Navigation("ReceivedNotifications");

                    b.Navigation("RecipientOrganization");

                    b.Navigation("SentNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
